[tool.poetry]
name = "agent-app"
version = "0.1.0"
description = ""
authors = ["annaic <rajan@annaic.co>"]
readme = "README.md"
packages = [{include = "agent_app"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
